site_name: Клуб анонимных джунов
site_description: Клуб анонимных джунов
theme: # Тема сайта, информация о ее параметрах
  name: material # Название темы
  logo: assets/images/logo.png
  favicon: assets/images/favicon.png
  font:
    text: Roboto # Шрифт текста
    code: Roboto Mono # Шрифт для текста кода 
  features:
    #- navigation.sections
    - navigation.path # Хлебные крошки
    - navigation.indexes # Позволяет создавать корневые страницы разделов меню. Корневая страница должна лежать в папке раздела и называться index.md. Пример использования корневых страниц приведен ниже в настройках nav
    - navigation.tabs # Верхнее меню
    - navigation.tabs.sticky # Фиксация верхнего меню
    - Navigation sections # Настройка спойлеров в левом меню
    - navigation.expand # Разворачивает спойлеры в левом меню по умолчанию
    - toc.integrate # Фиксирует оглавление страницы в левом меню
    - navigation.instant # Функция быстрой загрузки страниц
    - navigation.top # Добавляет кнопку «к началу» для быстрой обратной прокрутки страницы
    - search.suggest # Подсказки при вводе поискового запроса
    - search.highlight # Подсветка результатов поиска в тексте страницы
    - content.code.copy # Кнопка копирования в блоке кода
  language: ru # Язык
  palette: # Настройки светлой и тёмной тем
  # Светлая тема
    - scheme: default
      primary: blue grey
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Переключить на темную тему
    # Настройки тёмной темы
    - scheme: slate
      primary: black
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Переключить на светлую тему
nav: # Структура сайта
    - Главная страница: index.md
    - Дневные отчёты: DayCheck/Day0.md
    - Курсы: Course/index.md
    - Полезное: 
      - useful/index.md
      - Макрос для создания таблицы сокращений в Word: useful/Macword.md
    - Обзоры: 
      - reviews/index.md
      - Обзор любимых книг ч.1: reviews/time.md
    - Что почитать: 
      - WhatRead/index.md
      - Амир Вафин "Абсолютная дисциплина": WhatRead/amir.md
      - Кэл Ньюпорт "Хватит мечтать. Займись делом": WhatRead/dream.md
      - Джон П. Стрелеки "Кафе на краю земли": WhatRead/streleki.md
      - Бионический шрифт: WhatRead/bio.md
    - old: old/Day1-old.md
        
markdown_extensions: # Расширения markdown
  - admonition # Поддержка информационных панелей (сообщений типа «Внимание», «Совет», «Примечание», etc.)
  - footnotes # Поддержка встроенных сносок на страницах
  - attr_list # Использование html-атрибутов и CSS в элементах markdown
  - md_in_html # Поддержка markdown внутри html
  - def_list # Поддержка списков определений
  - pymdownx.tabbed # Использование вкладок (табов)
  - pymdownx.details # Использование спойлеров (катов)
  - pymdownx.highlight: # Подсветка синтаксиса в блоках кода
      anchor_linenums: true
  - pymdownx.superfences # Поддержка вложенных блоков кода
  - pymdownx.snippets # Использование заимствованного контента
  - pymdownx.emoji: # Иконки и эмодзи
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg