site_name: Anonymous Juniors Club
site_description: Anonymous Juniors Club
theme: # Тема сайта, информация о ее параметрах
  name: material # Название темы
  font:
    text: Roboto # Шрифт текста
    code: Roboto Mono # Шрифт для текста кода
  features:
    #- navigation.sections
    - navigation.path # Хлебные крошки
    - navigation.indexes # Позволяет создавать корневые страницы разделов меню. Корневая страница должна лежать в папке раздела и называться index.md. Пример использования корневых страниц приведен ниже в настройках nav
    #- navigation.tabs # Верхнее меню
    #- navigation.tabs.sticky # Фиксация верхнего меню
    #- Navigation sections # Настройка спойлеров в левом меню
    #- navigation.expand # Разворачивает спойлеры в левом меню по умолчанию
    #- toc.integrate # Фиксирует оглавление страницы в левом меню
    - navigation.instant # Функция быстрой загрузки страниц
    - navigation.top # Добавляет кнопку «к началу» для быстрой обратной прокрутки страницы
    - search.suggest # Подсказки при вводе поискового запроса
    - search.highlight # Подсветка результатов поиска в тексте страницы
    - content.code.copy # Кнопка копирования в блоке кода
  language: ru # Язык
  palette: # Настройки светлой и тёмной тем
    # Настройки светлой темы
    - scheme: default 
      toggle:
        icon: material/weather-sunny # Иконка для активации светлой темы
        name: Выключить солнышко # Всплывающий текст-подсказка
      primary: blue # Основной цвет
      accent: purple # Акцентный цвет
    # Настройки тёмной темы
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Позвать солнышко
      primary: deep purple
      accent: blue
nav: # Структура сайта
    - Главная страница: index.md
    - Дневные отчёты: 
      - Дневные отчёты/index.md
      - Old:
        - Old/index.md
        - День 1: Old/День 1 old.md
        - День 2: Old/День 2 old.md
        - День 3: Old/День 3 old.md
        - День 4: Old/День 4 old.md
        